name: Update from upstream and notify via Telegram

on:
  #schedule:
  #  - cron: 0 0 1 * *  # Run every 1st day of the month at 00:00
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Add upstream repository
        run: |
          git remote add upstream https://git.libremobileos.com/infrastructure/scripts.git
          git fetch upstream

      - name: Check for updates
        run: |
          git switch -c staging
          git pull upstream main --rebase --strategy-option theirs
          COMMIT_DIFF=$(git diff --name-only --cached | wc -l)
          if [ $COMMIT_DIFF -gt 0 ]; then
            git commit -m "Update from upstream"
            git push origin staging
          fi
          echo "COMMIT_DIFF=$COMMIT_DIFF" >> "$GITHUB_ENV"

      - name: Send Telegram notification
        run: |
          curl -X POST \
          https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage \
          -H 'Content-Type: application/json' \
          -d '{"chat_id": "${TELEGRAM_CHAT_ID}", "text": "Updated staging branch with '${COMMIT_DIFF}' new commits from upstream!"}'
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
